sudo: required
services:
  - docker

before_install:
  - docker build -t magscy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true magscy/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-ap-southeast-1-764913471004"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

  